CREATE TABLE IF NOT EXISTS `teacher` (
	`ID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`name`	TEXT NOT NULL,
	`alias`	TEXT,
	`qq`	INTEGER NOT NULL,
	`email`	TEXT NOT NULL,
	`createdTime`	TEXT NOT NULL,
	`lastModifiedTime`	TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS `students` (
	`ID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`name`	TEXT NOT NULL,
	`qq`	INTEGER NOT NULL UNIQUE,
	`email`	TEXT,
	`phone`	TEXT,
	`weChat`	TEXT,
	`createdTime`	TEXT NOT NULL,
	`lastModifiedTime`	TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS `signup` (
	`ID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`courseId`	INTEGER NOT NULL,
	`studentId`	INTEGER NOT NULL,
	`assistantId`	INTEGER NOT NULL,
	`payment`	INTEGER NOT NULL,
	`createdTime`	TEXT NOT NULL,
	`lastModifiedTime`	TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS `payment` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`courseId`	INTEGER NOT NULL,
	`studentId`	INTEGER NOT NULL,
	`type`	TEXT NOT NULL,
	`status`	TEXT
);
CREATE TABLE IF NOT EXISTS `course` (
	`ID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`teacherID`	INTEGER NOT NULL,
	`name`	TEXT NOT NULL,
	`price`	INTEGER NOT NULL,
	`createdTime`	TEXT NOT NULL,
	`lastModifiedTime`	TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS `assistant` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`name`	TEXT
);
